[package]
name = "ninja-force"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]

[dependencies.amethyst]
version = "0.12.0"
features = ["nightly"]

[features]
default = ["vulkan"]
empty = ["amethyst/empty"]
metal = ["amethyst/metal"]
vulkan = ["amethyst/vulkan"]
