[package]
name = "ninja-force"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
serde = {version = "*", features=["derive"]}
serde_derive = "*"

[dependencies.amethyst]
path = "../amethyst"

[features]
default = ["vulkan"]
empty = ["amethyst/empty"]
metal = ["amethyst/metal"]
vulkan = ["amethyst/vulkan"]
